import { fail } from "./errors.js";

/**
 * Typed, prefixed IDs.
 *
 * All IDs are generated by the application, never by the database (ADR-0001): no
 * `last_insert_rowid()` anywhere, so the PostgreSQL adapter is a drop-in. User-facing IDs use
 * per-investigation counters because a human has to read them in a proposal and type them into an
 * approval file. Where global uniqueness matters and no human reads the value (jobs), a random
 * suffix is used instead.
 */

export type InvestigationId = string & { readonly __brand: "InvestigationId" };
export type ExperimentId = string & { readonly __brand: "ExperimentId" };
export type ApprovedExperimentId = string & { readonly __brand: "ApprovedExperimentId" };
export type JobId = string & { readonly __brand: "JobId" };
export type RunId = string & { readonly __brand: "RunId" };
export type EventId = string & { readonly __brand: "EventId" };
export type ArtifactId = string & { readonly __brand: "ArtifactId" };
export type ApprovalId = string & { readonly __brand: "ApprovalId" };
export type LineageId = string & { readonly __brand: "LineageId" };
export type FlowId = string & { readonly __brand: "FlowId" };
export type SignatureId = string & { readonly __brand: "SignatureId" };
export type StatisticId = string & { readonly __brand: "StatisticId" };
export type FindingId = string & { readonly __brand: "FindingId" };
export type WorkerId = string & { readonly __brand: "WorkerId" };

const PATTERNS = {
  investigation: /^INV-\d{3,}$/,
  experiment: /^EXP-\d{3,}$/,
  approvedExperiment: /^AEXP-\d{3,}$/,
  job: /^JOB-[0-9a-z]{8,}$/,
  run: /^RUN-\d{1,6}$/,
  event: /^EV-\d{1,7}$/,
  artifact: /^[A-Z]+-[0-9A-Za-z._-]{1,64}$/,
  approval: /^APPR-\d{3,}$/,
  lineage: /^LIN-\d{6,}$/,
  flow: /^FLOW-\d{3,}$/,
  signature: /^A?SIG-\d{3,}$/,
  statistic: /^STAT-\d{3,}$/,
  finding: /^FIND-\d{3,}$/,
} as const;

function pad(n: number, width: number): string {
  const s = String(n);
  if (s.length > width) return s;
  return s.padStart(width, "0");
}

function assertPattern(value: string, pattern: RegExp, kind: string): void {
  if (!pattern.test(value)) {
    fail("INPUT_INVALID", `Malformed ${kind} id`, { context: { value, kind } });
  }
}

export function investigationId(n: number): InvestigationId {
  const v = `INV-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.investigation, "investigation");
  return v as InvestigationId;
}

export function experimentId(n: number): ExperimentId {
  const v = `EXP-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.experiment, "experiment");
  return v as ExperimentId;
}

export function approvedExperimentId(n: number): ApprovedExperimentId {
  const v = `AEXP-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.approvedExperiment, "approvedExperiment");
  return v as ApprovedExperimentId;
}

export function runId(n: number): RunId {
  const v = `RUN-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.run, "run");
  return v as RunId;
}

export function eventId(n: number): EventId {
  const v = `EV-${pad(n, 4)}`;
  assertPattern(v, PATTERNS.event, "event");
  return v as EventId;
}

export function approvalId(n: number): ApprovalId {
  const v = `APPR-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.approval, "approval");
  return v as ApprovalId;
}

export function lineageId(n: number): LineageId {
  const v = `LIN-${pad(n, 6)}`;
  assertPattern(v, PATTERNS.lineage, "lineage");
  return v as LineageId;
}

export function flowId(n: number): FlowId {
  const v = `FLOW-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.flow, "flow");
  return v as FlowId;
}

export function signatureId(n: number, approved = false): SignatureId {
  const v = `${approved ? "ASIG" : "SIG"}-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.signature, "signature");
  return v as SignatureId;
}

export function statisticId(n: number): StatisticId {
  const v = `STAT-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.statistic, "statistic");
  return v as StatisticId;
}

export function findingId(n: number): FindingId {
  const v = `FIND-${pad(n, 3)}`;
  assertPattern(v, PATTERNS.finding, "finding");
  return v as FindingId;
}

/**
 * Job ids carry a random suffix rather than a counter. Nothing human reads a job id, and a
 * collision across concurrent enqueues would be worse than an unreadable value.
 */
export function jobId(random: () => string): JobId {
  const v = `JOB-${random().slice(0, 12)}`;
  assertPattern(v, PATTERNS.job, "job");
  return v as JobId;
}

/**
 * Artifact ids are kind-prefixed so a reference is self-describing in a report: `TRACE-17`,
 * `SCREENSHOT-17-003`. The kind prefix is what reference validation check 5 keys off.
 */
export function artifactId(kindPrefix: string, ...parts: (string | number)[]): ArtifactId {
  const suffix = parts.length ? `-${parts.join("-")}` : "";
  const v = `${kindPrefix.toUpperCase().replace(/[^A-Z]/g, "")}${suffix}`;
  assertPattern(v, PATTERNS.artifact, "artifact");
  return v as ArtifactId;
}

export function workerId(hostname: string, pid: number, random: () => string): WorkerId {
  return `${hostname}:${pid}:${random().slice(0, 6)}` as WorkerId;
}

/** Parse the numeric part back out of a counter-based id. */
export function idSequence(value: string): number {
  const m = /-(\d+)$/.exec(value);
  if (!m || m[1] === undefined) {
    fail("INPUT_INVALID", "Id has no numeric sequence", { context: { value } });
  }
  return Number.parseInt(m[1], 10);
}

export const ID_PATTERNS = PATTERNS;
